name: im_client
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path: ^1.9.1
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  logger: ^2.6.0
  connectivity_plus: ^6.1.4
  intl: ^0.20.2
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.2.0
  window_size: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
flutter:
  assets:
    - assets/images/
  uses-material-design: true
